[project]
name = "sqlmesh-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlt[duckdb,motherduck]>=1.4.1",
    "duckdb>=1.1.3",
    "sqlmesh[web]>=0.138.0",
    "yfinance",
]
