[project]
name = "sqlmesh-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sqlmesh>=0.138.0",
    "yfinance>=0.2.50",
]
