gateways:
  prod:
    connection:
      type: motherduck
      database: dlt_test_db
  
  local:
    connection:
      type: motherduck
      catalogs:
        local_db:
          type: duckdb
          path: "local_db.db"
        remote_db:
          type: motherduck
          path: "md:dlt_test_db"

default_gateway: prod

model_defaults:
  dialect: duckdb
  start: 2024-12-08
